version: "3"
services:
    web:
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-windows-express"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"